name: 🐛 Signaler un bug
description: Signalez un bug pour nous aider à améliorer Papillon
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Etapes à reproduire
      description: "Étapes pour reproduire le bug :"
      placeholder: |
        1. [ex: Etape 1]
        2. [ex: Etape 1]
      value: |
        1. 
        2. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportement attendu
      description: Une description claire et concise de ce que vous attendiez.
    validations:
      required: true
  - type: input
    attributes:
      label: Appareil
      placeholder: iPhone X
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      placeholder: iOS 10
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      placeholder: "3.7.2"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environnement
      options:
        - PWA Dev (app.pronote.plus)
        - PWA Stable (v3.pronote.plus)
        - Androïd APK
        - iOS Profil d'installation
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Captures d'écran / vidéo"
      description: "Si possible, ajoutez des captures d'écran pour aider à expliquer votre problème."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Contexte supplémentaire
      description: Des liens ? Des références ? Tout ce qui peut nous donner plus de détails sur le problème que vous rencontrez !
    validations:
      required: false
